lmbench: fix build error with gcc-15
* see more details
  http://errors.yoctoproject.org/Errors/Details/851798/

    lat_rpc.c:172:1: error: conflicting types for 'client_rpc_xact_1'; have 'char *(char *, CLIENT *)' {aka 'char *(char *, struct __rpc_client *)'}
    172 | client_rpc_xact_1(char *argp, CLIENT *clnt)
        | ^~~~~~~~~~~~~~~~~
    bench.h:349:14: note: previous declaration of 'client_rpc_xact_1' with type 'char *(void)'
    349 | extern char *client_rpc_xact_1();
        |              ^~~~~~~~~~~~~~~~~
    lat_rpc.c: In function 'rpc_xact_1':
    lat_rpc.c:189:1: warning: old-style function definition [-Wold-style-definition]
    189 | rpc_xact_1(msg, transp)
        | ^~~~~~~~~~
    lat_rpc.c:192:1: error: number of arguments doesn't match prototype
    192 | {
        | ^
    bench.h:348:14: error: prototype declaration
    348 | extern char *rpc_xact_1();
        |              ^~~~~~~~~~

  Fix errors due to old-style function declarations

  The code was using old-style function declarations without proper prototypes,
  which causes compilation errors with newer GCC versions. This patch updates
  the function declarations to use modern C syntax with proper parameter types.

Signed-off-by: mark.yang <mark.yang@lge.com>